# Generated by Django 4.0.2 on 2022-02-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ürünün Adı', max_length=80, verbose_name='Ürün Adı')),
                ('describtion', models.TextField()),
                ('image', models.ImageField(default='products/broken-1.png', upload_to='products/%Y/%m/%d/')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
