# Generated by Django 4.0.2 on 2022-02-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='describtion',
            new_name='description',
        ),
    ]
